CREATE TABLE public.certifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  issuer TEXT NOT NULL,
  url TEXT NOT NULL,
  field TEXT NOT NULL, -- matches career_profiles.industry / job industry naming
  level TEXT NOT NULL DEFAULT 'beginner', -- beginner | intermediate | advanced
  cost TEXT NOT NULL DEFAULT 'free', -- free | freemium | paid
  duration_estimate TEXT,
  skills_taught JSONB NOT NULL DEFAULT '[]'::jsonb,
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT ON public.certifications TO anon, authenticated;
GRANT ALL ON public.certifications TO service_role;
ALTER TABLE public.certifications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Certifications public read" ON public.certifications FOR SELECT USING (true);
CREATE POLICY "Admins manage certifications" ON public.certifications FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));

INSERT INTO public.certifications (title, issuer, url, field, level, cost, duration_estimate, skills_taught, description) VALUES
('Google Data Analytics Professional Certificate', 'Google (via Coursera)', 'https://www.coursera.org/professional-certificates/google-data-analytics', 'Data & AI', 'beginner', 'freemium', '3-6 months', '["SQL", "Tableau", "Spreadsheets", "Data Cleaning", "Data Visualization"]'::jsonb, 'Google''s own entry point into data analytics; no degree required. Free to audit, financial aid available for the paid certificate.'),
('Google Advanced Data Analytics Professional Certificate', 'Google (via Coursera)', 'https://www.coursera.org/professional-certificates/google-advanced-data-analytics', 'Data & AI', 'intermediate', 'freemium', '3-6 months', '["Python", "Statistics", "Regression Models", "Machine Learning"]'::jsonb, 'Follow-on to the entry-level Data Analytics certificate; goes into Python and applied ML.'),
('Meta Front-End Developer Professional Certificate', 'Meta (via Coursera)', 'https://www.coursera.org/professional-certificates/meta-front-end-developer', 'Software Engineering', 'beginner', 'freemium', '5-7 months', '["HTML", "CSS", "JavaScript", "React"]'::jsonb, 'Built by Meta engineers; covers the practical front-end stack most junior roles ask for.'),
('CS50: Introduction to Computer Science', 'Harvard University (via edX)', 'https://cs50.harvard.edu/x/', 'Software Engineering', 'beginner', 'free', 'Self-paced, ~10-20 hrs/week', '["C", "Python", "SQL", "Algorithms", "Data Structures"]'::jsonb, 'The famous free Harvard CS intro course. Certificate available for a small fee; the course itself is free.'),
('Google IT Support Professional Certificate', 'Google (via Coursera)', 'https://www.coursera.org/professional-certificates/google-it-support', 'Software Engineering', 'beginner', 'freemium', '3-6 months', '["Troubleshooting", "Networking", "System Administration", "Customer Support"]'::jsonb, 'Entry point into IT support roles; no prior experience required.'),
('Google Cybersecurity Professional Certificate', 'Google (via Coursera)', 'https://www.coursera.org/professional-certificates/google-cybersecurity', 'Software Engineering', 'beginner', 'freemium', '3-6 months', '["Security Fundamentals", "SIEM Tools", "Python", "Linux"]'::jsonb, 'Entry-level cybersecurity analyst training built by Google.'),
('Responsive Web Design Certification', 'freeCodeCamp', 'https://www.freecodecamp.org/learn/2022/responsive-web-design/', 'Software Engineering', 'beginner', 'free', '~300 hours self-paced', '["HTML", "CSS", "Flexbox", "Grid", "Accessibility"]'::jsonb, 'Completely free, project-based, widely recognized by hiring managers who know the platform.'),
('Google UX Design Professional Certificate', 'Google (via Coursera)', 'https://www.coursera.org/professional-certificates/google-ux-design', 'Product & Design', 'beginner', 'freemium', '3-6 months', '["User Research", "Wireframing", "Figma", "Prototyping"]'::jsonb, 'Builds a portfolio of 3 end-to-end UX projects; widely accepted by employers as a portfolio-building path.'),
('Canva Design School Courses', 'Canva', 'https://www.canva.com/designschool/', 'Creative & Media', 'beginner', 'free', 'A few hours per course', '["Graphic Design Fundamentals", "Branding", "Social Media Design"]'::jsonb, 'Free short courses covering practical design skills using Canva''s own tools.'),
('HubSpot Inbound Marketing Certification', 'HubSpot Academy', 'https://academy.hubspot.com/courses/inbound-marketing', 'Marketing & Growth', 'beginner', 'free', '~5 hours', '["Content Marketing", "Social Media", "Inbound Strategy"]'::jsonb, 'Free, short, and one of the most commonly listed certifications on marketing resumes.'),
('HubSpot Social Media Marketing Certification', 'HubSpot Academy', 'https://academy.hubspot.com/courses/social-media-strategy', 'Marketing & Growth', 'beginner', 'free', '~5 hours', '["Social Strategy", "Content Calendars", "Analytics"]'::jsonb, 'Free certification focused on building and measuring a social media strategy.'),
('Google Digital Marketing & E-commerce Certificate', 'Google (via Coursera)', 'https://www.coursera.org/professional-certificates/google-digital-marketing-ecommerce', 'Marketing & Growth', 'beginner', 'freemium', '3-6 months', '["SEO", "SEM", "Email Marketing", "E-commerce Strategy"]'::jsonb, 'Covers the marketing funnel end to end, including Google Ads and Analytics tools.'),
('HubSpot Inbound Sales Certification', 'HubSpot Academy', 'https://academy.hubspot.com/courses/inbound-sales', 'Sales & Business Development', 'beginner', 'free', '~5 hours', '["Sales Process", "Prospecting", "CRM"]'::jsonb, 'Free, practical certification widely recognized in SME and startup sales roles.'),
('Google Project Management Professional Certificate', 'Google (via Coursera)', 'https://www.coursera.org/professional-certificates/google-project-management', 'Operations', 'beginner', 'freemium', '3-6 months', '["Agile", "Scrum", "Project Planning", "Risk Management"]'::jsonb, 'Coursework counts toward PMI''s CAPM certification requirements at a discount.'),
('CAPM — Certified Associate in Project Management', 'Project Management Institute (PMI)', 'https://www.pmi.org/certifications/associate-capm', 'Operations', 'intermediate', 'paid', 'Exam-based; ~23 hrs prerequisite education', '["Project Lifecycle", "Agile & Waterfall Basics"]'::jsonb, 'Entry-level PMI credential; requires a high school diploma/GED and 23 hours of PM education before sitting the exam. Around $225-300 to sit.'),
('Diploma in Project Management', 'Alison', 'https://alison.com/tag/project-management', 'Operations', 'beginner', 'free', 'Self-paced', '["PMBOK Basics", "Scheduling", "Risk Management"]'::jsonb, 'Free, self-paced; Alison has issued over 5 million certificates and is widely recognized in MENA, South Asia, and Africa job markets.'),
('Google Analytics Certification (GA4)', 'Google Skillshop', 'https://skillshop.withgoogle.com/', 'Marketing & Growth', 'beginner', 'free', 'A few hours', '["Google Analytics 4", "Conversion Tracking", "Reporting"]'::jsonb, 'Free official Google certification; GA4 is now the industry-standard analytics platform.'),
('Networking Basics', 'Cisco Networking Academy (Skills for All)', 'https://skillsforall.com/course/networking-basics', 'Software Engineering', 'beginner', 'free', '~70 hours', '["Networking Fundamentals", "IP Addressing", "Troubleshooting"]'::jsonb, 'Free course leading to a Credly-verified digital badge, one of the most trusted entry credentials in IT.'),
('Google Certified Educator Level 1', 'Google for Education', 'https://teachercenter.withgoogle.com/', 'Education', 'beginner', 'free', 'Self-paced', '["Google Workspace for Education", "EdTech Integration"]'::jsonb, 'Free training and certification exam for teachers using Google tools in the classroom.'),
('OpenWHO Public Health Courses', 'World Health Organization (OpenWHO)', 'https://openwho.org/', 'Healthcare', 'beginner', 'free', 'Varies by course', '["Public Health Fundamentals", "Epidemiology Basics", "Health Emergency Response"]'::jsonb, 'WHO''s own free course platform; each completed course includes a free certificate of completion.'),
('Financial Modeling & Valuation Fundamentals', 'Corporate Finance Institute (CFI)', 'https://corporatefinanceinstitute.com/', 'Finance & Accounting', 'intermediate', 'freemium', 'Self-paced', '["Financial Modeling", "Valuation", "Excel"]'::jsonb, 'Widely referenced in finance job postings; free introductory resources with paid certificate tracks.');
