CREATE TABLE public.career_paths (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  field TEXT NOT NULL,
  description TEXT NOT NULL,
  entry_titles JSONB NOT NULL DEFAULT '[]'::jsonb, -- typical job titles at entry level
  core_skills JSONB NOT NULL DEFAULT '[]'::jsonb,
  typical_progression JSONB NOT NULL DEFAULT '[]'::jsonb, -- e.g. ["Junior", "Mid", "Senior", "Lead"]
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT ON public.career_paths TO anon, authenticated;
GRANT ALL ON public.career_paths TO service_role;
ALTER TABLE public.career_paths ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Career paths public read" ON public.career_paths FOR SELECT USING (true);
CREATE POLICY "Admins manage career paths" ON public.career_paths FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));

INSERT INTO public.career_paths (title, field, description, entry_titles, core_skills, typical_progression) VALUES
('Software Engineering', 'Software Engineering', 'Design, build, and maintain the systems and applications behind digital products. One of the most in-demand paths globally, with strong remote-work availability.', '["Junior Software Developer", "Software Engineering Intern", "Associate Developer"]'::jsonb, '["JavaScript/TypeScript or Python", "Git", "Databases (SQL)", "Problem solving", "APIs"]'::jsonb, '["Junior Engineer", "Mid-level Engineer", "Senior Engineer", "Staff/Lead Engineer", "Engineering Manager"]'::jsonb),
('Data Analytics', 'Data & AI', 'Turn raw data into decisions — reporting, dashboards, and analysis that shapes how a business operates. A strong entry point into the broader data field.', '["Data Analyst", "Junior Data Analyst", "Business Intelligence Analyst"]'::jsonb, '["SQL", "Excel/Spreadsheets", "Data visualization (Tableau/Power BI)", "Statistics basics"]'::jsonb, '["Junior Analyst", "Data Analyst", "Senior Analyst", "Analytics Manager", "Head of Data"]'::jsonb),
('Machine Learning / AI', 'Data & AI', 'Build the models and systems behind AI-powered products. Usually requires stronger math/stats foundations than data analytics.', '["Junior ML Engineer", "AI Research Assistant", "Data Scientist (entry)"]'::jsonb, '["Python", "Statistics", "Machine learning fundamentals", "Data pipelines"]'::jsonb, '["Junior ML Engineer", "ML Engineer", "Senior ML Engineer", "ML Lead", "Head of AI"]'::jsonb),
('Product Design (UX/UI)', 'Product & Design', 'Shape how digital products look, feel, and function — from user research through to polished interfaces.', '["Junior Product Designer", "UX/UI Designer", "Design Intern"]'::jsonb, '["Figma", "User research", "Wireframing/prototyping", "Visual design fundamentals"]'::jsonb, '["Junior Designer", "Product Designer", "Senior Designer", "Design Lead", "Head of Design"]'::jsonb),
('Digital Marketing', 'Marketing & Growth', 'Grow a brand or product''s audience and revenue through content, paid media, SEO, and campaign strategy.', '["Digital Marketing Associate", "Marketing Coordinator", "Content Marketing Intern"]'::jsonb, '["SEO basics", "Social media strategy", "Content writing", "Analytics tools (GA4)"]'::jsonb, '["Marketing Associate", "Marketing Specialist", "Marketing Manager", "Head of Growth"]'::jsonb),
('Sales & Business Development', 'Sales & Business Development', 'Drive revenue through prospecting, relationship-building, and closing deals — one of the most transferable skill sets across industries.', '["Sales Development Rep", "Business Development Associate", "Account Executive (entry)"]'::jsonb, '["CRM tools", "Negotiation", "Prospecting/outreach", "Communication"]'::jsonb, '["SDR/BDR", "Account Executive", "Senior AE", "Sales Manager", "Head of Sales"]'::jsonb),
('Finance & Accounting', 'Finance & Accounting', 'Manage the numbers that keep organizations running — from bookkeeping and reporting through to financial strategy.', '["Accounts Assistant", "Junior Accountant", "Finance Intern"]'::jsonb, '["Excel", "Basic accounting principles", "Financial reporting", "Attention to detail"]'::jsonb, '["Accounts Assistant", "Accountant", "Senior Accountant", "Finance Manager", "CFO"]'::jsonb),
('Human Resources', 'HR & People', 'Support the people side of an organization — hiring, onboarding, employee relations, and culture.', '["HR Assistant", "Recruitment Coordinator", "People Ops Associate"]'::jsonb, '["Communication", "Recruitment basics", "HRIS tools", "Employee relations"]'::jsonb, '["HR Assistant", "HR Generalist", "HR Business Partner", "Head of People"]'::jsonb),
('Operations', 'Operations', 'Keep the day-to-day machinery of a business running — logistics, process, vendor management, and project execution.', '["Operations Associate", "Junior Project Coordinator", "Operations Intern"]'::jsonb, '["Project management basics", "Process improvement", "Communication", "Spreadsheets"]'::jsonb, '["Operations Associate", "Operations Manager", "Senior Operations Manager", "COO"]'::jsonb),
('Customer Support', 'Customer Support', 'Be the front line between a company and its users — solving problems and shaping how customers experience a product.', '["Customer Support Associate", "Support Agent", "Customer Success Intern"]'::jsonb, '["Communication", "Troubleshooting", "Support tools (Zendesk etc.)", "Patience under pressure"]'::jsonb, '["Support Associate", "Senior Support", "Customer Success Manager", "Head of Support"]'::jsonb),
('Healthcare (Clinical)', 'Healthcare', 'Direct patient-facing clinical roles — nursing, clinical officer work, and allied health paths.', '["Registered Nurse", "Clinical Officer", "Healthcare Assistant"]'::jsonb, '["Clinical training/certification", "Patient care", "Documentation", "Communication"]'::jsonb, '["Entry Clinical Role", "Registered Practitioner", "Senior Practitioner", "Department Head"]'::jsonb),
('Education & Teaching', 'Education', 'Shape the next generation through classroom teaching, curriculum design, or educational technology.', '["Teaching Assistant", "Junior Teacher", "Curriculum Assistant"]'::jsonb, '["Subject expertise", "Classroom management", "Curriculum design", "Communication"]'::jsonb, '["Teaching Assistant", "Teacher", "Senior Teacher", "Head of Department", "Principal"]'::jsonb),
('Legal', 'Legal', 'Support legal work in a firm, company, or government body — research, drafting, and eventually advocacy.', '["Legal Intern", "Paralegal", "Legal Assistant"]'::jsonb, '["Legal research", "Document drafting", "Attention to detail", "Communication"]'::jsonb, '["Paralegal", "Associate Advocate", "Senior Advocate", "Partner"]'::jsonb),
('Creative & Media', 'Creative & Media', 'Tell stories and build brands through video, design, writing, or content production.', '["Content Creator", "Junior Video Editor", "Graphic Design Intern"]'::jsonb, '["Editing/design tools (Adobe suite)", "Storytelling", "Content strategy", "Time management"]'::jsonb, '["Junior Creative", "Creative Specialist", "Senior Creative", "Creative Director"]'::jsonb),
('Skilled Trades', 'Skilled Trades', 'Hands-on technical work — electrical, HVAC, and other trades that stay in steady demand regardless of the broader economy.', '["Apprentice Electrician", "Trainee Technician", "Trades Assistant"]'::jsonb, '["Trade-specific certification", "Safety codes", "Hands-on technical skill", "Problem solving"]'::jsonb, '["Apprentice", "Journeyman/Technician", "Master Tradesperson", "Own Contracting Business"]'::jsonb);
